services:
  - type: web
    name: arena-booking-bot
    env: python
    region: frankfurt
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: bash start.sh
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: DB_URL
        sync: false
      - key: ADMIN_IDS
        sync: false
      - key: BASE_URL
        value: https://digital-arena-njok.onrender.com
      - key: REDIS_HOST
        value: localhost
      - key: PYTHON_VERSION
        value: 3.11.5
