"""Initial migration

Revision ID: f4a15e181f30
Revises: 
Create Date: 2026-02-12 19:12:07.470697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4a15e181f30'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # SQLite often complains about dropping non-existent indices on initial migrations
    def safe_drop_index(index_name, table_name):
        try:
            op.drop_index(op.f(index_name), table_name=table_name)
        except Exception:
            pass
            
    safe_drop_index('idx_booking_availability', 'bookings')
    safe_drop_index('idx_booking_club_time', 'bookings')
    safe_drop_index('idx_booking_status_time', 'bookings')
    safe_drop_index('idx_booking_user_time', 'bookings')
    
    # op.alter_column('computers', 'image_url',
    #            existing_type=sa.TEXT(),
    #            type_=sa.String(),
    #            existing_nullable=True)
               
    safe_drop_index('idx_computer_club_active', 'computers')
    
    # op.alter_column('restaurant_tables', 'id',
    #            existing_type=sa.INTEGER(),
    #            nullable=False,
    #            autoincrement=True)
               
    safe_drop_index('idx_table_club_active', 'restaurant_tables')
    safe_drop_index('ix_restaurant_tables_club_id', 'restaurant_tables')
    
    # op.alter_column('users', 'tg_id',
    #            existing_type=sa.INTEGER(),
    #            type_=sa.BigInteger(),
    #            existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'tg_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.create_index(op.f('ix_restaurant_tables_club_id'), 'restaurant_tables', ['club_id'], unique=False)
    op.create_index(op.f('idx_table_club_active'), 'restaurant_tables', ['club_id', 'is_active'], unique=False)
    op.alter_column('restaurant_tables', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.create_index(op.f('idx_computer_club_active'), 'computers', ['club_id', 'is_active'], unique=False)
    op.alter_column('computers', 'image_url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.create_index(op.f('idx_booking_user_time'), 'bookings', ['user_id', 'start_time'], unique=False)
    op.create_index(op.f('idx_booking_status_time'), 'bookings', ['status', 'start_time'], unique=False)
    op.create_index(op.f('idx_booking_club_time'), 'bookings', ['club_id', 'start_time'], unique=False)
    op.create_index(op.f('idx_booking_availability'), 'bookings', ['club_id', 'computer_name', 'status', 'start_time', 'end_time'], unique=False)
    # ### end Alembic commands ###
